import { defineCRUD } from "@repo/crud";

export const FrontPageSettingsCRUD = defineCRUD({
  model: "frontPageSettings",
  label: "Settings",
  mode: "keyValue", // switches UI to settings-style form
  navGroup: "Front Page", // optional sidebar group
  icon: "Settings",
  supportedLocales: ["en", "id"],
  defaultLocale: "en",
  fields: [
    {
      namespace: "general",
      name: "logo",
      type: "image",
      label: "Logo",
      tab: "General",
      uploadUrl: "/api/upload?path=uploads/logo",
      width: "half",
      localized: false,
    },
    {
      namespace: "general",
      name: "favicon",
      type: "image",
      label: "Favicon",
      tab: "General",
      uploadUrl: "/api/upload?path=uploads/favicon",
      width: "half",
      localized: false,
    },
    {
      namespace: "general",
      name: "site_name",
      type: "text",
      label: "Site Name",
      tab: "General",
      localized: false,
    },
    {
      namespace: "header",
      name: "headerCtaLabel",
      type: "text",
      label: "Header CTA Label",
      tab: "Header",
      width: "half",
    },
    {
      namespace: "header",
      name: "headerCtaUrl",
      type: "text",
      label: "Header CTA URL",
      tab: "Header",
      width: "half",
      localized: false,
    },
    {
      namespace: "footer",
      name: "footerTagline",
      type: "textarea",
      label: "Footer Tagline",
      tab: "Footer",
    },
    {
      namespace: "footer",
      name: "footerExploreHeading",
      type: "text",
      label: "Footer Explore Heading",
      tab: "Footer",
      width: "half",
    },
    {
      namespace: "footer",
      name: "footerContactHeading",
      type: "text",
      label: "Footer Contact Heading",
      tab: "Footer",
      width: "half",
    },
    {
      namespace: "footer",
      name: "footerFollowHeading",
      type: "text",
      label: "Footer Follow Heading",
      tab: "Footer",
      width: "half",
    },
    {
      namespace: "footer",
      name: "footerCopyrightText",
      type: "text",
      label: "Copyright Text",
      tab: "Footer",
    },
    {
      namespace: "footer",
      name: "footerMadeText",
      type: "text",
      label: "Footer Made Text",
      tab: "Footer",
    },
    {
      namespace: "contact",
      name: "contactPhoneLabel",
      type: "text",
      label: "Phone Number",
      tab: "Contact",
      width: "half",
      localized: false,
    },
    {
      namespace: "contact",
      name: "contactPhoneUrl",
      type: "text",
      label: "Phone URL",
      tab: "Contact",
      width: "half",
      localized: false,
    },
    {
      namespace: "contact",
      name: "contactEmailLabel",
      type: "text",
      label: "Email Display Text",
      tab: "Contact",
      width: "half",
      localized: false,
    },
    {
      namespace: "contact",
      name: "contactEmailUrl",
      type: "text",
      label: "Email URL",
      tab: "Contact",
      width: "half",
      localized: false,
    },
    {
      namespace: "contact",
      name: "contactInstagramLabel",
      type: "text",
      label: "Instagram Display Text",
      tab: "Contact",
      width: "half",
      localized: false,
    },
    {
      namespace: "contact",
      name: "contactInstagramUrl",
      type: "text",
      label: "Instagram URL",
      tab: "Contact",
      width: "half",
      localized: false,
    },
    {
      namespace: "contact",
      name: "contactWhatsappLabel",
      type: "text",
      label: "WhatsApp Display Text",
      tab: "Contact",
      width: "half",
      localized: false,
    },
    {
      namespace: "contact",
      name: "contactWhatsappUrl",
      type: "text",
      label: "WhatsApp URL",
      tab: "Contact",
      width: "half",
      localized: false,
    },
    {
      namespace: "contact",
      name: "contactWorkingHours",
      type: "text",
      label: "Working Hours",
      tab: "Contact",
    },
    {
      namespace: "social",
      name: "socialInstagramUrl",
      type: "text",
      label: "Follow Instagram URL",
      tab: "Footer",
      width: "half",
      localized: false,
    },
    {
      namespace: "social",
      name: "socialWhatsappUrl",
      type: "text",
      label: "Follow WhatsApp URL",
      tab: "Footer",
      width: "half",
      localized: false,
    },
    {
      namespace: "social",
      name: "socialEmailUrl",
      type: "text",
      label: "Follow Email URL",
      tab: "Footer",
      width: "half",
      localized: false,
    },
    {
      namespace: "seo",
      name: "meta_title",
      type: "text",
      label: "Meta Title",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "meta_description",
      type: "text",
      label: "Meta Description",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "meta_keywords",
      type: "text",
      label: "Meta Keywords",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "seoHomePageSeo",
      type: "separator",
      label: "Home Page SEO",
      tab: "SEO",
      showInTable: false,
    },
    {
      namespace: "seo",
      name: "homePageSeoMetaTitle",
      type: "text",
      label: "Meta Title Home Page",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "homePageSeoMetaDescription",
      type: "text",
      label: "Meta Description Home Page",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "homePageSeoMetaKeywords",
      type: "text",
      label: "Meta Keywords Home Page",
      tab: "SEO",
    },
    {
      namespace: "scripts",
      name: "headerScript",
      type: "textarea",
      label: "Header Script",
      tab: "Scripts",
      localized: false,
    },
    {
      namespace: "scripts",
      name: "footerScript",
      type: "textarea",
      label: "Footer Script",
      tab: "Scripts",
      localized: false,
    },
    {
      namespace: "hero",
      name: "heroSection",
      type: "separator",
      label: "Hero Section",
      tab: "Home",
      showInTable: false,
    },
    {
      namespace: "hero",
      name: "heroStamp",
      type: "text",
      label: "Stamp Text",
      tab: "Home",
    },
    {
      namespace: "hero",
      name: "heroTitleLine1",
      type: "text",
      label: "Title Line 1",
      tab: "Home",
    },
    {
      namespace: "hero",
      name: "heroTitleLine2",
      type: "text",
      label: "Title Line 2",
      tab: "Home",
    },
    {
      namespace: "hero",
      name: "heroTitleLine3",
      type: "text",
      label: "Title Line 3",
      tab: "Home",
    },
    {
      namespace: "hero",
      name: "heroTitleHighlightIndex",
      type: "select",
      label: "Highlighted Title Line",
      tab: "Home",
      width: "half",
      options: [
        { label: "Line 1", value: "0" },
        { label: "Line 2", value: "1" },
        { label: "Line 3", value: "2" },
      ],
      default: "1",
      localized: false,
    },
    {
      namespace: "hero",
      name: "heroSubtitle",
      type: "textarea",
      label: "Subtitle",
      tab: "Home",
    },
    {
      namespace: "hero",
      name: "heroCtaPrimaryLabel",
      type: "text",
      label: "Primary CTA Label",
      tab: "Home",
      width: "half",
    },
    {
      namespace: "hero",
      name: "heroCtaSecondaryLabel",
      type: "text",
      label: "Secondary CTA Label",
      tab: "Home",
      width: "half",
    },
    {
      namespace: "hero",
      name: "heroCtaSecondaryUrl",
      type: "text",
      label: "Secondary CTA URL",
      tab: "Home",
      width: "half",
      localized: false,
    },
    {
      namespace: "hero",
      name: "heroImage",
      type: "image",
      label: "Hero Image (Mascot)",
      tab: "Home",
      uploadUrl: "/api/upload?path=uploads/hero",
      localized: false,
    },
    {
      namespace: "hero",
      name: "heroScrollText",
      type: "text",
      label: "Scroll Down Text",
      tab: "Home",
    },
    {
      namespace: "work",
      name: "workSection",
      type: "separator",
      label: "Latest Work",
      tab: "Home",
      showInTable: false,
    },
    {
      namespace: "work",
      name: "workEye",
      type: "text",
      label: "Eyebrow",
      tab: "Home",
    },
    {
      namespace: "work",
      name: "workHeadLine1",
      type: "text",
      label: "Heading Line 1",
      tab: "Home",
    },
    {
      namespace: "work",
      name: "workHeadLine2",
      type: "text",
      label: "Heading Line 2",
      tab: "Home",
    },
    {
      namespace: "work",
      name: "workHeadHighlightIndex",
      type: "select",
      label: "Highlighted Heading Line",
      tab: "Home",
      width: "half",
      default: "1",
      localized: false,
      options: [
        { label: "Line 1", value: "0" },
        { label: "Line 2", value: "1" },
      ],
    },
    {
      namespace: "work",
      name: "workIntro",
      type: "textarea",
      label: "Intro Paragraph",
      tab: "Home",
    },
    {
      namespace: "work",
      name: "homeFeaturedPortfolioId",
      type: "select",
      label: "Featured Portfolio",
      tab: "Home",
      note: "Pick one portfolio to feature on the home page. Display order follows Portfolio position.",
      localized: false,
      optionsFrom: {
        model: "portfolio",
        valueField: "id",
        labelField: "name",
        orderBy: { position: "asc" },
      },
    },
    {
      namespace: "pkg",
      name: "pkgSection",
      type: "separator",
      label: "Pilih Paket",
      tab: "Home",
      showInTable: false,
    },
    {
      namespace: "pkg",
      name: "pkgEye",
      type: "text",
      label: "Eyebrow",
      tab: "Home",
    },
    {
      namespace: "pkg",
      name: "pkgHeadLine1",
      type: "text",
      label: "Heading Line 1",
      tab: "Home",
    },
    {
      namespace: "pkg",
      name: "pkgHeadLine2",
      type: "text",
      label: "Heading Line 2",
      tab: "Home",
    },
    {
      namespace: "pkg",
      name: "pkgHeadHighlightIndex",
      type: "select",
      label: "Highlighted Heading Line",
      tab: "Home",
      width: "half",
      default: "1",
      localized: false,
      options: [
        { label: "Line 1", value: "0" },
        { label: "Line 2", value: "1" },
      ],
    },
    {
      namespace: "pkg",
      name: "pkgIntro",
      type: "textarea",
      label: "Intro Paragraph",
      tab: "Home",
    },
    {
      namespace: "pkg",
      name: "pkgNote",
      type: "textarea",
      label: "Promo Note (footer of section)",
      tab: "Home",
    },
    {
      namespace: "whyForkumi",
      name: "whyForkumiSection",
      type: "separator",
      label: "Why Forkumi Stats",
      tab: "Why Forkumi",
      showInTable: false,
    },
    {
      namespace: "whyForkumi",
      name: "whyForkumiEye",
      type: "text",
      label: "Eyebrow",
      tab: "Why Forkumi",
    },
    {
      namespace: "whyForkumi",
      name: "whyForkumiHead",
      type: "text",
      label: "Heading",
      tab: "Why Forkumi",
    },
    { namespace: "whyForkumi", name: "stat1Num", type: "text", label: "Stat 1 Number", tab: "Why Forkumi", width: "half", localized: false },
    { namespace: "whyForkumi", name: "stat1Unit", type: "text", label: "Stat 1 Unit", tab: "Why Forkumi", width: "half" },
    { namespace: "whyForkumi", name: "stat1Label", type: "text", label: "Stat 1 Label", tab: "Why Forkumi" },
    {
      namespace: "whyForkumi",
      name: "stat1Color",
      type: "text",
      label: "Stat 1 Background (hex or CSS)",
      tab: "Why Forkumi",
      width: "half",
      default: "var(--card-purple)",
      note: "Card background. Use any CSS color: hex (#FF0000), var(--purple), etc.",
      localized: false,
    },
    {
      namespace: "whyForkumi",
      name: "stat1TextColor",
      type: "text",
      label: "Stat 1 Text Color (hex or CSS)",
      tab: "Why Forkumi",
      width: "half",
      default: "var(--purple)",
      note: "Color of the big number. Pick a saturated tone for readability (e.g. var(--purple), #8E6FC6).",
      localized: false,
    },
    { namespace: "whyForkumi", name: "stat2Num", type: "text", label: "Stat 2 Number", tab: "Why Forkumi", width: "half", localized: false },
    { namespace: "whyForkumi", name: "stat2Unit", type: "text", label: "Stat 2 Unit", tab: "Why Forkumi", width: "half" },
    { namespace: "whyForkumi", name: "stat2Label", type: "text", label: "Stat 2 Label", tab: "Why Forkumi" },
    {
      namespace: "whyForkumi",
      name: "stat2Color",
      type: "text",
      label: "Stat 2 Background (hex or CSS)",
      tab: "Why Forkumi",
      width: "half",
      default: "var(--card-rose)",
      note: "Card background.",
      localized: false,
    },
    {
      namespace: "whyForkumi",
      name: "stat2TextColor",
      type: "text",
      label: "Stat 2 Text Color (hex or CSS)",
      tab: "Why Forkumi",
      width: "half",
      default: "var(--rose)",
      note: "Color of the big number.",
      localized: false,
    },
    { namespace: "whyForkumi", name: "stat3Num", type: "text", label: "Stat 3 Number", tab: "Why Forkumi", width: "half", localized: false },
    { namespace: "whyForkumi", name: "stat3Unit", type: "text", label: "Stat 3 Unit", tab: "Why Forkumi", width: "half" },
    { namespace: "whyForkumi", name: "stat3Label", type: "text", label: "Stat 3 Label", tab: "Why Forkumi" },
    {
      namespace: "whyForkumi",
      name: "stat3Color",
      type: "text",
      label: "Stat 3 Background (hex or CSS)",
      tab: "Why Forkumi",
      width: "half",
      default: "var(--card-yellow)",
      note: "Card background.",
      localized: false,
    },
    {
      namespace: "whyForkumi",
      name: "stat3TextColor",
      type: "text",
      label: "Stat 3 Text Color (hex or CSS)",
      tab: "Why Forkumi",
      width: "half",
      default: "#EFC75E",
      note: "Color of the big number.",
      localized: false,
    },
    { namespace: "whyForkumi", name: "stat4Num", type: "text", label: "Stat 4 Number", tab: "Why Forkumi", width: "half", localized: false },
    { namespace: "whyForkumi", name: "stat4Unit", type: "text", label: "Stat 4 Unit", tab: "Why Forkumi", width: "half" },
    { namespace: "whyForkumi", name: "stat4Label", type: "text", label: "Stat 4 Label", tab: "Why Forkumi" },
    {
      namespace: "whyForkumi",
      name: "stat4Color",
      type: "text",
      label: "Stat 4 Background (hex or CSS)",
      tab: "Why Forkumi",
      width: "half",
      default: "var(--card-purple)",
      note: "Card background.",
      localized: false,
    },
    {
      namespace: "whyForkumi",
      name: "stat4TextColor",
      type: "text",
      label: "Stat 4 Text Color (hex or CSS)",
      tab: "Why Forkumi",
      width: "half",
      default: "var(--purple)",
      note: "Color of the big number.",
      localized: false,
    },
    {
      namespace: "whySubscribe",
      name: "whySubscribeSection",
      type: "separator",
      label: "Why Subscribe",
      tab: "Why Subscribe",
      showInTable: false,
    },
    {
      namespace: "whySubscribe",
      name: "whySubEye",
      type: "text",
      label: "Eyebrow",
      tab: "Why Subscribe",
    },
    {
      namespace: "whySubscribe",
      name: "whySubHeadLine1",
      type: "text",
      label: "Heading Line 1",
      tab: "Why Subscribe",
    },
    {
      namespace: "whySubscribe",
      name: "whySubHeadLine2",
      type: "text",
      label: "Heading Line 2",
      tab: "Why Subscribe",
    },
    {
      namespace: "whySubscribe",
      name: "whySubHeadHighlightIndex",
      type: "select",
      label: "Highlighted Heading Line",
      tab: "Why Subscribe",
      width: "half",
      default: "1",
      localized: false,
      options: [
        { label: "Line 1", value: "0" },
        { label: "Line 2", value: "1" },
      ],
    },
    {
      namespace: "whySubscribe",
      name: "whySubIntro",
      type: "textarea",
      label: "Intro Paragraph",
      tab: "Why Subscribe",
    },
    {
      namespace: "whySubscribe",
      name: "whySubLine",
      type: "text",
      label: "Tagline",
      tab: "Why Subscribe",
    },
  ],
});
