import { defineCRUD } from "@repo/crud";

export const FrontPageSettingsCRUD = defineCRUD({
  model: "frontPageSettings",
  label: "Settings",
  mode: "keyValue", // switches UI to settings-style form
  navGroup: "Front Page", // optional sidebar group
  icon: "Settings",
  supportedLocales: ["en", "id"],
  defaultLocale: "en",
  fields: [
    {
      namespace: "general",
      name: "logo",
      type: "image",
      label: "Logo",
      tab: "General",
      uploadUrl: "/api/upload?path=uploads/logo",
      width: "half",
      localized: false,
    },
    {
      namespace: "general",
      name: "logoFooter",
      type: "image",
      label: "Logo (Footer)",
      tab: "General",
      uploadUrl: "/api/upload?path=uploads/logo-footer",
      width: "half",
      localized: false,
    },
    {
      namespace: "general",
      name: "favicon",
      type: "image",
      label: "Favicon",
      tab: "General",
      uploadUrl: "/api/upload?path=uploads/favicon",
      width: "half",
      localized: false,
    },
    {
      namespace: "general",
      name: "site_name",
      type: "text",
      label: "Site Name",
      tab: "General",
      localized: false,
    },
    {
      namespace: "header",
      name: "headerCtaLabel",
      type: "text",
      label: "Header CTA Label",
      tab: "Header",
      width: "half",
    },
    {
      namespace: "header",
      name: "headerCtaUrl",
      type: "text",
      label: "Header CTA URL",
      tab: "Header",
      width: "half",
      localized: false,
    },
    {
      namespace: "footer",
      name: "footerTagline",
      type: "textarea",
      label: "Footer Tagline",
      tab: "Footer",
    },
    {
      namespace: "footer",
      name: "footerExploreHeading",
      type: "text",
      label: "Footer Explore Heading",
      tab: "Footer",
      width: "half",
    },
    {
      namespace: "footer",
      name: "footerContactHeading",
      type: "text",
      label: "Footer Contact Heading",
      tab: "Footer",
      width: "half",
    },
    {
      namespace: "footer",
      name: "footerFollowHeading",
      type: "text",
      label: "Footer Follow Heading",
      tab: "Footer",
      width: "half",
    },
    {
      namespace: "footer",
      name: "footerCopyrightText",
      type: "text",
      label: "Copyright Text",
      tab: "Footer",
    },
    {
      namespace: "footer",
      name: "footerMadeText",
      type: "text",
      label: "Footer Made Text",
      tab: "Footer",
    },
    {
      namespace: "contact",
      name: "contactPhoneLabel",
      type: "text",
      label: "Phone Number",
      tab: "Contact",
      width: "half",
      localized: false,
    },
    {
      namespace: "contact",
      name: "contactPhoneUrl",
      type: "text",
      label: "Phone URL",
      tab: "Contact",
      width: "half",
      localized: false,
    },
    {
      namespace: "contact",
      name: "contactEmailLabel",
      type: "text",
      label: "Email Display Text",
      tab: "Contact",
      width: "half",
      localized: false,
    },
    {
      namespace: "contact",
      name: "contactEmailUrl",
      type: "text",
      label: "Email URL",
      tab: "Contact",
      width: "half",
      localized: false,
    },
    {
      namespace: "contact",
      name: "contactInstagramLabel",
      type: "text",
      label: "Instagram Display Text",
      tab: "Contact",
      width: "half",
      localized: false,
    },
    {
      namespace: "contact",
      name: "contactInstagramUrl",
      type: "text",
      label: "Instagram URL",
      tab: "Contact",
      width: "half",
      localized: false,
    },
    {
      namespace: "contact",
      name: "contactWhatsappLabel",
      type: "text",
      label: "WhatsApp Display Text",
      tab: "Contact",
      width: "half",
      localized: false,
    },
    {
      namespace: "contact",
      name: "contactWhatsappUrl",
      type: "text",
      label: "WhatsApp URL",
      tab: "Contact",
      width: "half",
      localized: false,
    },
    {
      namespace: "contact",
      name: "contactWorkingHours",
      type: "text",
      label: "Working Hours",
      tab: "Contact",
    },
    {
      namespace: "contact",
      name: "contactSuccessMessage",
      type: "text",
      label: "Success Message",
      tab: "Contact",
      note: "Shown after a successful contact submission.",
    },
    {
      namespace: "contact",
      name: "contactErrorMessage",
      type: "text",
      label: "Error Message",
      tab: "Contact",
      note: "Shown when the contact submission fails. Per-locale fallback is built in.",
    },
    {
      namespace: "social",
      name: "socialInstagramUrl",
      type: "text",
      label: "Follow Instagram URL",
      tab: "Footer",
      width: "half",
      localized: false,
    },
    {
      namespace: "social",
      name: "socialWhatsappUrl",
      type: "text",
      label: "Follow WhatsApp URL",
      tab: "Footer",
      width: "half",
      localized: false,
    },
    {
      namespace: "social",
      name: "socialEmailUrl",
      type: "text",
      label: "Follow Email URL",
      tab: "Footer",
      width: "half",
      localized: false,
    },
    {
      namespace: "seo",
      name: "meta_title",
      type: "text",
      label: "Meta Title",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "meta_description",
      type: "text",
      label: "Meta Description",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "meta_keywords",
      type: "text",
      label: "Meta Keywords",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "seoHomePageSeo",
      type: "separator",
      label: "Home Page SEO",
      tab: "SEO",
      showInTable: false,
    },
    {
      namespace: "seo",
      name: "homePageSeoMetaTitle",
      type: "text",
      label: "Meta Title Home Page",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "homePageSeoMetaDescription",
      type: "text",
      label: "Meta Description Home Page",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "homePageSeoMetaKeywords",
      type: "text",
      label: "Meta Keywords Home Page",
      tab: "SEO",
    },
    {
      namespace: "scripts",
      name: "headerScript",
      type: "textarea",
      label: "Header Script",
      tab: "Scripts",
      localized: false,
    },
    {
      namespace: "scripts",
      name: "footerScript",
      type: "textarea",
      label: "Footer Script",
      tab: "Scripts",
      localized: false,
    },
    {
      namespace: "hero",
      name: "heroSection",
      type: "separator",
      label: "Hero Section",
      tab: "Home",
      showInTable: false,
    },
    {
      namespace: "hero",
      name: "heroStamp",
      type: "text",
      label: "Stamp Text",
      tab: "Home",
    },
    {
      namespace: "hero",
      name: "heroTitleLine1",
      type: "text",
      label: "Title Line 1",
      tab: "Home",
    },
    {
      namespace: "hero",
      name: "heroTitleLine2",
      type: "text",
      label: "Title Line 2",
      tab: "Home",
    },
    {
      namespace: "hero",
      name: "heroTitleLine3",
      type: "text",
      label: "Title Line 3",
      tab: "Home",
    },
    {
      namespace: "hero",
      name: "heroTitleHighlightIndex",
      type: "select",
      label: "Highlighted Title Line",
      tab: "Home",
      width: "half",
      options: [
        { label: "Line 1", value: "0" },
        { label: "Line 2", value: "1" },
        { label: "Line 3", value: "2" },
      ],
      default: "1",
      localized: false,
    },
    {
      namespace: "hero",
      name: "heroSubtitle",
      type: "textarea",
      label: "Subtitle",
      tab: "Home",
    },
    {
      namespace: "hero",
      name: "heroCtaPrimaryLabel",
      type: "text",
      label: "Primary CTA Label",
      tab: "Home",
      width: "half",
    },
    {
      namespace: "hero",
      name: "heroCtaSecondaryLabel",
      type: "text",
      label: "Secondary CTA Label",
      tab: "Home",
      width: "half",
    },
    {
      namespace: "hero",
      name: "heroCtaSecondaryUrl",
      type: "text",
      label: "Secondary CTA URL",
      tab: "Home",
      width: "half",
      localized: false,
    },
    {
      namespace: "hero",
      name: "heroImage",
      type: "image",
      label: "Hero Image (Mascot)",
      tab: "Home",
      uploadUrl: "/api/upload?path=uploads/hero",
      localized: false,
    },
    {
      namespace: "hero",
      name: "heroScrollText",
      type: "text",
      label: "Scroll Down Text",
      tab: "Home",
    },
    {
      namespace: "whyForkumi",
      name: "whyForkumiHomeSection",
      type: "separator",
      label: "Why Forkumi (Home Stats)",
      tab: "Home",
      showInTable: false,
    },
    {
      namespace: "whyForkumi",
      name: "whyForkumiHeadLine1",
      type: "text",
      label: "Heading Line 1",
      tab: "Home",
    },
    {
      namespace: "whyForkumi",
      name: "whyForkumiHeadLine2",
      type: "text",
      label: "Heading Line 2",
      tab: "Home",
    },
    {
      namespace: "whyForkumi",
      name: "whyForkumiHeadHighlightIndex",
      type: "select",
      label: "Highlighted Heading Line",
      tab: "Home",
      width: "half",
      default: "1",
      localized: false,
      options: [
        { label: "Line 1", value: "0" },
        { label: "Line 2", value: "1" },
      ],
    },
    {
      namespace: "work",
      name: "workSection",
      type: "separator",
      label: "Latest Work",
      tab: "Home",
      showInTable: false,
    },
    {
      namespace: "work",
      name: "workEye",
      type: "text",
      label: "Eyebrow",
      tab: "Home",
    },
    {
      namespace: "work",
      name: "workHeadLine1",
      type: "text",
      label: "Heading Line 1",
      tab: "Home",
    },
    {
      namespace: "work",
      name: "workHeadLine2",
      type: "text",
      label: "Heading Line 2",
      tab: "Home",
    },
    {
      namespace: "work",
      name: "workHeadHighlightIndex",
      type: "select",
      label: "Highlighted Heading Line",
      tab: "Home",
      width: "half",
      default: "1",
      localized: false,
      options: [
        { label: "Line 1", value: "0" },
        { label: "Line 2", value: "1" },
      ],
    },
    {
      namespace: "work",
      name: "workIntro",
      type: "textarea",
      label: "Intro Paragraph",
      tab: "Home",
    },
    {
      namespace: "work",
      name: "homeFeaturedPortfolioId",
      type: "select",
      label: "Featured Portfolio",
      tab: "Home",
      note: "Pick one portfolio to feature on the home page. Display order follows Portfolio position.",
      localized: false,
      optionsFrom: {
        model: "portfolio",
        valueField: "id",
        labelField: "name",
        orderBy: { position: "asc" },
      },
    },
    { namespace: "work", name: "featuredLabelsSection", type: "separator", label: "Featured Portfolio Labels", tab: "Home", showInTable: false },
    { namespace: "work", name: "featuredBadgeFeatured", type: "text", label: "Badge — Featured Item", tab: "Home", width: "half", note: "Shown on the first/hero portfolio card." },
    { namespace: "work", name: "featuredBadgeOther", type: "text", label: "Badge — Other Items", tab: "Home", width: "half" },
    { namespace: "work", name: "featuredCtaVisit", type: "text", label: "CTA — Visit Website", tab: "Home", width: "half" },
    { namespace: "work", name: "featuredCtaDiscuss", type: "text", label: "CTA — Discuss a Project", tab: "Home", width: "half" },
    { namespace: "work", name: "featuredCtaSeeAll", type: "text", label: "CTA — See All Work", tab: "Home", width: "half" },
    { namespace: "work", name: "featuredWhatsappFallback", type: "text", label: "WhatsApp Fallback URL (no portfolio link)", tab: "Home", note: "Used when the featured portfolio has no website URL.", localized: false },
    { namespace: "faqHome", name: "faqHomeSection", type: "separator", label: "Home FAQ Heading", tab: "Home", showInTable: false },
    { namespace: "faqHome", name: "faqHomeEye", type: "text", label: "Eyebrow", tab: "Home", width: "half" },
    { namespace: "faqHome", name: "faqHomeHeadLine1", type: "text", label: "Heading Line 1", tab: "Home", width: "half" },
    { namespace: "faqHome", name: "faqHomeHeadLine2", type: "text", label: "Heading Line 2", tab: "Home", width: "half" },
    { namespace: "faqHome", name: "faqHomeHeadHighlightIndex", type: "select", label: "Highlighted Heading Line", tab: "Home", width: "half", default: "1", localized: false, options: [{ label: "Line 1", value: "0" }, { label: "Line 2", value: "1" }] },
    { namespace: "services", name: "servicesSection", type: "separator", label: "Page Header", tab: "Services", showInTable: false },
    { namespace: "services", name: "servicesPageLead", type: "textarea", label: "Lead (under H1)", tab: "Services" },
    { namespace: "services", name: "servicesH1Line1", type: "text", label: "H1 Line 1", tab: "Services", width: "half" },
    { namespace: "services", name: "servicesH1Line2", type: "text", label: "H1 Line 2", tab: "Services", width: "half" },
    { namespace: "services", name: "servicesH1HighlightIndex", type: "select", label: "Highlighted H1 Line", tab: "Services", width: "half", default: "1", localized: false, options: [{ label: "Line 1", value: "0" }, { label: "Line 2", value: "1" }] },
    { namespace: "services", name: "servicesCatalogSection", type: "separator", label: "Layanan Lengkap", tab: "Services", showInTable: false },
    { namespace: "services", name: "servicesCatalogEye", type: "text", label: "Eyebrow", tab: "Services", width: "half" },
    { namespace: "services", name: "servicesCatalogHeadLine1", type: "text", label: "Heading Line 1", tab: "Services", width: "half" },
    { namespace: "services", name: "servicesCatalogHeadLine2", type: "text", label: "Heading Line 2", tab: "Services", width: "half" },
    { namespace: "services", name: "servicesCatalogHeadHighlightIndex", type: "select", label: "Highlighted Heading Line", tab: "Services", width: "half", default: "1", localized: false, options: [{ label: "Line 1", value: "0" }, { label: "Line 2", value: "1" }] },
    { namespace: "services", name: "servicesIndustriesSection", type: "separator", label: "Industri", tab: "Services", showInTable: false },
    { namespace: "services", name: "servicesIndustriesEye", type: "text", label: "Eyebrow", tab: "Services", width: "half" },
    { namespace: "services", name: "servicesIndustriesHeadLine1", type: "text", label: "Heading Line 1", tab: "Services", width: "half" },
    { namespace: "services", name: "servicesIndustriesHeadLine2", type: "text", label: "Heading Line 2", tab: "Services", width: "half" },
    { namespace: "services", name: "servicesIndustriesHeadHighlightIndex", type: "select", label: "Highlighted Heading Line", tab: "Services", width: "half", default: "1", localized: false, options: [{ label: "Line 1", value: "0" }, { label: "Line 2", value: "1" }] },
    { namespace: "services", name: "servicesIndustriesIntro", type: "textarea", label: "Intro Paragraph", tab: "Services" },
    { namespace: "portfolio", name: "portfolioHeaderSection", type: "separator", label: "Page Header", tab: "Portfolio", showInTable: false },
    { namespace: "portfolio", name: "portfolioH1Line1", type: "text", label: "H1 Line 1", tab: "Portfolio", width: "half" },
    { namespace: "portfolio", name: "portfolioH1Line2", type: "text", label: "H1 Line 2", tab: "Portfolio", width: "half" },
    { namespace: "portfolio", name: "portfolioH1HighlightIndex", type: "select", label: "Highlighted H1 Line", tab: "Portfolio", width: "half", default: "1", localized: false, options: [{ label: "Line 1", value: "0" }, { label: "Line 2", value: "1" }] },
    { namespace: "portfolio", name: "portfolioPageLead", type: "textarea", label: "Lead (under H1)", tab: "Portfolio" },
    { namespace: "portfolio", name: "portfolioIgSection", type: "separator", label: "Instagram CTA Strip", tab: "Portfolio", showInTable: false },
    { namespace: "portfolio", name: "portfolioIgHeading", type: "text", label: "Heading", tab: "Portfolio" },
    { namespace: "portfolio", name: "portfolioIgParagraph", type: "textarea", label: "Paragraph", tab: "Portfolio" },
    { namespace: "packages", name: "packagesPageSection", type: "separator", label: "Page Header", tab: "Packages", showInTable: false },
    { namespace: "packages", name: "packagesH1Line1", type: "text", label: "H1 Line 1", tab: "Packages", width: "half" },
    { namespace: "packages", name: "packagesH1Line2", type: "text", label: "H1 Line 2", tab: "Packages", width: "half" },
    { namespace: "packages", name: "packagesH1HighlightIndex", type: "select", label: "Highlighted H1 Line", tab: "Packages", width: "half", default: "1", localized: false, options: [{ label: "Line 1", value: "0" }, { label: "Line 2", value: "1" }] },
    { namespace: "packages", name: "packagesPageLead", type: "textarea", label: "Lead (under H1)", tab: "Packages" },
    { namespace: "packages", name: "packagesIncludedSection", type: "separator", label: "Yang Kamu Dapat", tab: "Packages", showInTable: false },
    { namespace: "packages", name: "packagesIncludedEye", type: "text", label: "Eyebrow", tab: "Packages", width: "half" },
    { namespace: "packages", name: "packagesIncludedHeadLine1", type: "text", label: "Heading Line 1", tab: "Packages", width: "half" },
    { namespace: "packages", name: "packagesIncludedHeadLine2", type: "text", label: "Heading Line 2", tab: "Packages", width: "half" },
    { namespace: "packages", name: "packagesIncludedHeadHighlightIndex", type: "select", label: "Highlighted Heading Line", tab: "Packages", width: "half", default: "1", localized: false, options: [{ label: "Line 1", value: "0" }, { label: "Line 2", value: "1" }] },
    { namespace: "packages", name: "packagesTermsSection", type: "separator", label: "Syarat & Pembayaran", tab: "Packages", showInTable: false },
    { namespace: "packages", name: "packagesTermsEye", type: "text", label: "Eyebrow", tab: "Packages", width: "half" },
    { namespace: "packages", name: "packagesTermsHeadLine1", type: "text", label: "Heading Line 1", tab: "Packages", width: "half" },
    { namespace: "packages", name: "packagesTermsHeadLine2", type: "text", label: "Heading Line 2", tab: "Packages", width: "half" },
    { namespace: "packages", name: "packagesTermsHeadHighlightIndex", type: "select", label: "Highlighted Heading Line", tab: "Packages", width: "half", default: "1", localized: false, options: [{ label: "Line 1", value: "0" }, { label: "Line 2", value: "1" }] },
    { namespace: "about", name: "aboutPageSection", type: "separator", label: "Page Header", tab: "About", showInTable: false },
    { namespace: "about", name: "aboutH1Line1", type: "text", label: "H1 Line 1", tab: "About", width: "half" },
    { namespace: "about", name: "aboutH1Line2", type: "text", label: "H1 Line 2", tab: "About", width: "half" },
    { namespace: "about", name: "aboutH1HighlightIndex", type: "select", label: "Highlighted H1 Line", tab: "About", width: "half", default: "1", localized: false, options: [{ label: "Line 1", value: "0" }, { label: "Line 2", value: "1" }] },
    { namespace: "about", name: "pageAboutLead", type: "textarea", label: "Lead (under H1)", tab: "About" },
    { namespace: "about", name: "aboutVisionSection", type: "separator", label: "Visi & Misi", tab: "About", showInTable: false },
    { namespace: "about", name: "aboutVisionEye", type: "text", label: "Eyebrow", tab: "About" },
    { namespace: "about", name: "aboutVisionHeading", type: "text", label: "Visi (heading)", tab: "About" },
    { namespace: "about", name: "aboutVisionParagraph", type: "textarea", label: "Visi (paragraph)", tab: "About" },
    { namespace: "about", name: "aboutMissionHeading", type: "text", label: "Misi (heading)", tab: "About" },
    { namespace: "about", name: "aboutMissionParagraph", type: "textarea", label: "Misi (paragraph)", tab: "About" },
    { namespace: "about", name: "aboutTrustSection", type: "separator", label: "Jaminan (Trust)", tab: "About", showInTable: false },
    { namespace: "about", name: "aboutTrustEye", type: "text", label: "Eyebrow", tab: "About", width: "half" },
    { namespace: "about", name: "aboutTrustHeadLine1", type: "text", label: "Heading Line 1", tab: "About", width: "half" },
    { namespace: "about", name: "aboutTrustHeadLine2", type: "text", label: "Heading Line 2", tab: "About", width: "half" },
    { namespace: "about", name: "aboutTrustHeadHighlightIndex", type: "select", label: "Highlighted Heading Line", tab: "About", width: "half", default: "1", localized: false, options: [{ label: "Line 1", value: "0" }, { label: "Line 2", value: "1" }] },
    { namespace: "about", name: "aboutTrustIntro", type: "textarea", label: "Intro Paragraph", tab: "About" },
    { namespace: "about", name: "aboutProcessSection", type: "separator", label: "Process (shared with /services)", tab: "About", showInTable: false },
    { namespace: "about", name: "processSectionEye", type: "text", label: "Eyebrow", tab: "About", width: "half" },
    { namespace: "about", name: "processSectionHeadLine1", type: "text", label: "Heading Line 1", tab: "About", width: "half" },
    { namespace: "about", name: "processSectionHeadLine2", type: "text", label: "Heading Line 2", tab: "About", width: "half" },
    { namespace: "about", name: "processSectionHeadHighlightIndex", type: "select", label: "Highlighted Heading Line", tab: "About", width: "half", default: "1", localized: false, options: [{ label: "Line 1", value: "0" }, { label: "Line 2", value: "1" }] },
    { namespace: "contact", name: "contactPageSection", type: "separator", label: "Page Header", tab: "Contact", showInTable: false },
    { namespace: "contact", name: "contactH1Line1", type: "text", label: "H1 Line 1", tab: "Contact", width: "half" },
    { namespace: "contact", name: "contactH1Line2", type: "text", label: "H1 Line 2", tab: "Contact", width: "half" },
    { namespace: "contact", name: "contactH1HighlightIndex", type: "select", label: "Highlighted H1 Line", tab: "Contact", width: "half", default: "1", localized: false, options: [{ label: "Line 1", value: "0" }, { label: "Line 2", value: "1" }] },
    { namespace: "contact", name: "contactIntro", type: "textarea", label: "Lead (under H1)", tab: "Contact" },
    { namespace: "contact", name: "contactFormSection", type: "separator", label: "Form Labels", tab: "Contact", showInTable: false },
    { namespace: "contact", name: "contactFormHeading", type: "text", label: "Form Heading", tab: "Contact" },
    { namespace: "contact", name: "contactFieldName", type: "text", label: "Name Label", tab: "Contact", width: "half" },
    { namespace: "contact", name: "contactFieldEmail", type: "text", label: "Email Label", tab: "Contact", width: "half" },
    { namespace: "contact", name: "contactFieldPkg", type: "text", label: "Plan Label", tab: "Contact", width: "half" },
    { namespace: "contact", name: "contactFieldMessage", type: "text", label: "Message Label", tab: "Contact", width: "half" },
    { namespace: "contact", name: "contactFieldSubmit", type: "text", label: "Submit Button Label", tab: "Contact", width: "half" },
    { namespace: "contact", name: "contactHoursHeading", type: "text", label: "Working Hours Heading", tab: "Contact" },
    { namespace: "cta", name: "ctaSection", type: "separator", label: "CTA Band (every page)", tab: "Home", showInTable: false, note: "Drives the bottom CTA strip on home/services/portfolio/packages/about." },
    { namespace: "cta", name: "ctaEye", type: "text", label: "Eyebrow", tab: "Home", width: "half" },
    { namespace: "cta", name: "ctaHeadLine1", type: "text", label: "Heading Line 1", tab: "Home", width: "half" },
    { namespace: "cta", name: "ctaHeadLine2", type: "text", label: "Heading Line 2", tab: "Home", width: "half" },
    { namespace: "cta", name: "ctaHeadHighlightIndex", type: "select", label: "Highlighted Heading Line", tab: "Home", width: "half", default: "1", localized: false, options: [{ label: "Line 1", value: "0" }, { label: "Line 2", value: "1" }] },
    { namespace: "cta", name: "ctaSub", type: "textarea", label: "Subtitle", tab: "Home" },
    { namespace: "cta", name: "ctaBtnPrimaryLabel", type: "text", label: "Primary CTA Label", tab: "Home", width: "half" },
    { namespace: "cta", name: "ctaBtnSecondaryLabel", type: "text", label: "Secondary CTA Label", tab: "Home", width: "half" },
    { namespace: "cta", name: "ctaBtnPrimaryUrl", type: "text", label: "Primary CTA URL", tab: "Home", note: "Usually a WhatsApp deep link.", localized: false },
    { namespace: "cta", name: "ctaBtnSecondaryUrl", type: "text", label: "Secondary CTA URL", tab: "Home", localized: false },
    {
      namespace: "pkg",
      name: "pkgSection",
      type: "separator",
      label: "Pilih Paket",
      tab: "Home",
      showInTable: false,
    },
    {
      namespace: "pkg",
      name: "pkgEye",
      type: "text",
      label: "Eyebrow",
      tab: "Home",
    },
    {
      namespace: "pkg",
      name: "pkgHeadLine1",
      type: "text",
      label: "Heading Line 1",
      tab: "Home",
    },
    {
      namespace: "pkg",
      name: "pkgHeadLine2",
      type: "text",
      label: "Heading Line 2",
      tab: "Home",
    },
    {
      namespace: "pkg",
      name: "pkgHeadHighlightIndex",
      type: "select",
      label: "Highlighted Heading Line",
      tab: "Home",
      width: "half",
      default: "1",
      localized: false,
      options: [
        { label: "Line 1", value: "0" },
        { label: "Line 2", value: "1" },
      ],
    },
    {
      namespace: "pkg",
      name: "pkgIntro",
      type: "textarea",
      label: "Intro Paragraph",
      tab: "Home",
    },
    {
      namespace: "pkg",
      name: "pkgNote",
      type: "textarea",
      label: "Promo Note (footer of section)",
      tab: "Home",
    },
    {
      namespace: "whyForkumi",
      name: "whyForkumiSection",
      type: "separator",
      label: "Why Forkumi Stats",
      tab: "Why Forkumi",
      showInTable: false,
    },
    {
      namespace: "whyForkumi",
      name: "whyForkumiEye",
      type: "text",
      label: "Eyebrow",
      tab: "Why Forkumi",
    },
    {
      namespace: "whyForkumi",
      name: "whyForkumiHead",
      type: "text",
      label: "Heading (legacy single line, prefer Line 1/2 in Home tab)",
      tab: "Why Forkumi",
    },
    { namespace: "whyForkumi", name: "stat1Num", type: "text", label: "Stat 1 Number", tab: "Why Forkumi", width: "half", localized: false },
    { namespace: "whyForkumi", name: "stat1Unit", type: "text", label: "Stat 1 Unit", tab: "Why Forkumi", width: "half" },
    { namespace: "whyForkumi", name: "stat1Label", type: "text", label: "Stat 1 Label", tab: "Why Forkumi" },
    {
      namespace: "whyForkumi",
      name: "stat1Color",
      type: "text",
      label: "Stat 1 Background (hex or CSS)",
      tab: "Why Forkumi",
      width: "half",
      default: "var(--card-purple)",
      note: "Card background. Use any CSS color: hex (#FF0000), var(--purple), etc.",
      localized: false,
    },
    {
      namespace: "whyForkumi",
      name: "stat1TextColor",
      type: "text",
      label: "Stat 1 Text Color (hex or CSS)",
      tab: "Why Forkumi",
      width: "half",
      default: "var(--purple)",
      note: "Color of the big number. Pick a saturated tone for readability (e.g. var(--purple), #8E6FC6).",
      localized: false,
    },
    { namespace: "whyForkumi", name: "stat2Num", type: "text", label: "Stat 2 Number", tab: "Why Forkumi", width: "half", localized: false },
    { namespace: "whyForkumi", name: "stat2Unit", type: "text", label: "Stat 2 Unit", tab: "Why Forkumi", width: "half" },
    { namespace: "whyForkumi", name: "stat2Label", type: "text", label: "Stat 2 Label", tab: "Why Forkumi" },
    {
      namespace: "whyForkumi",
      name: "stat2Color",
      type: "text",
      label: "Stat 2 Background (hex or CSS)",
      tab: "Why Forkumi",
      width: "half",
      default: "var(--card-rose)",
      note: "Card background.",
      localized: false,
    },
    {
      namespace: "whyForkumi",
      name: "stat2TextColor",
      type: "text",
      label: "Stat 2 Text Color (hex or CSS)",
      tab: "Why Forkumi",
      width: "half",
      default: "var(--rose)",
      note: "Color of the big number.",
      localized: false,
    },
    { namespace: "whyForkumi", name: "stat3Num", type: "text", label: "Stat 3 Number", tab: "Why Forkumi", width: "half", localized: false },
    { namespace: "whyForkumi", name: "stat3Unit", type: "text", label: "Stat 3 Unit", tab: "Why Forkumi", width: "half" },
    { namespace: "whyForkumi", name: "stat3Label", type: "text", label: "Stat 3 Label", tab: "Why Forkumi" },
    {
      namespace: "whyForkumi",
      name: "stat3Color",
      type: "text",
      label: "Stat 3 Background (hex or CSS)",
      tab: "Why Forkumi",
      width: "half",
      default: "var(--card-yellow)",
      note: "Card background.",
      localized: false,
    },
    {
      namespace: "whyForkumi",
      name: "stat3TextColor",
      type: "text",
      label: "Stat 3 Text Color (hex or CSS)",
      tab: "Why Forkumi",
      width: "half",
      default: "#EFC75E",
      note: "Color of the big number.",
      localized: false,
    },
    { namespace: "whyForkumi", name: "stat4Num", type: "text", label: "Stat 4 Number", tab: "Why Forkumi", width: "half", localized: false },
    { namespace: "whyForkumi", name: "stat4Unit", type: "text", label: "Stat 4 Unit", tab: "Why Forkumi", width: "half" },
    { namespace: "whyForkumi", name: "stat4Label", type: "text", label: "Stat 4 Label", tab: "Why Forkumi" },
    {
      namespace: "whyForkumi",
      name: "stat4Color",
      type: "text",
      label: "Stat 4 Background (hex or CSS)",
      tab: "Why Forkumi",
      width: "half",
      default: "var(--card-purple)",
      note: "Card background.",
      localized: false,
    },
    {
      namespace: "whyForkumi",
      name: "stat4TextColor",
      type: "text",
      label: "Stat 4 Text Color (hex or CSS)",
      tab: "Why Forkumi",
      width: "half",
      default: "var(--purple)",
      note: "Color of the big number.",
      localized: false,
    },
    {
      namespace: "whySubscribe",
      name: "whySubscribeSection",
      type: "separator",
      label: "Why Subscribe",
      tab: "Why Subscribe",
      showInTable: false,
    },
    {
      namespace: "whySubscribe",
      name: "whySubEye",
      type: "text",
      label: "Eyebrow",
      tab: "Why Subscribe",
    },
    {
      namespace: "whySubscribe",
      name: "whySubHeadLine1",
      type: "text",
      label: "Heading Line 1",
      tab: "Why Subscribe",
    },
    {
      namespace: "whySubscribe",
      name: "whySubHeadLine2",
      type: "text",
      label: "Heading Line 2",
      tab: "Why Subscribe",
    },
    {
      namespace: "whySubscribe",
      name: "whySubHeadHighlightIndex",
      type: "select",
      label: "Highlighted Heading Line",
      tab: "Why Subscribe",
      width: "half",
      default: "1",
      localized: false,
      options: [
        { label: "Line 1", value: "0" },
        { label: "Line 2", value: "1" },
      ],
    },
    {
      namespace: "whySubscribe",
      name: "whySubIntro",
      type: "textarea",
      label: "Intro Paragraph",
      tab: "Why Subscribe",
    },
    {
      namespace: "whySubscribe",
      name: "whySubLine",
      type: "text",
      label: "Tagline",
      tab: "Why Subscribe",
    },
  ],
});
