import { defineCRUD } from "@repo/crud";

export const FrontPageSettingsCRUD = defineCRUD({
  model: "frontPageSettings",
  label: "Settings",
  mode: "keyValue", // switches UI to settings-style form
  navGroup: "Front Page", // optional sidebar group
  icon: "Settings",
  fields: [
    {
      namespace: "general",
      name: "logo",
      type: "image",
      label: "Logo (Light Mode)",
      tab: "General",
      uploadUrl: "/api/upload?path=uploads/logo",
      width: "half",
    },
    {
      namespace: "general",
      name: "favicon",
      type: "image",
      label: "Favicon",
      tab: "General",
      uploadUrl: "/api/upload?path=uploads/favicon",
      width: "half",
    },
    {
      namespace: "general",
      name: "site_name",
      type: "text",
      label: "Site Name",
      tab: "General",
    },
    {
      namespace: "general",
      name: "search_placeholder",
      type: "text",
      label: "Search Placeholder",
      tab: "General",
    },
    {
      namespace: "general",
      name: "footer_motto",
      type: "richtext",
      label: "Footer Motto",
      tab: "General",
    },
    {
      namespace: "general",
      name: "footer_copyright",
      type: "text",
      label: "Footer Copyright",
      tab: "General",
    },
    {
      namespace: "general",
      name: "sidebar_image",
      type: "image",
      label: "Sidebar Image",
      tab: "General",
      uploadUrl: "/api/upload?path=uploads/sidebar",
    },
    {
      namespace: "general",
      name: "sidebar_title",
      type: "text",
      label: "Sidebar Title",
      tab: "General",
    },
    {
      namespace: "general",
      name: "feedbackSectionTitle",
      type: "text",
      label: "Feedback Section Title",
      tab: "General",
    },
    {
      namespace: "general",
      name: "feedbackSectionContent",
      type: "richtext",
      label: "Feedback Section Content",
      tab: "General",
    },
    {
      namespace: "general",
      name: "noteSectionTitle",
      type: "text",
      label: "Note Section Title",
      tab: "General",
    },
    {
      namespace: "general",
      name: "noteSectionContent",
      type: "richtext",
      label: "Note Section Content",
      tab: "General",
    },
    {
      namespace: "general",
      name: "noteSectionBy",
      type: "richtext",
      label: "Note Section By",
      tab: "General",
    },
    {
      namespace: "homePage",
      name: "homepage_section_pin_blog_id",
      type: "select",
      label: "Pin blog",
      tab: "Home Page",
      optionsFrom: {
        model: "blog",
        valueField: "id",
        labelField: "title",
        where: { status: "published" },
        orderBy: { title: "asc" },
      },
    },
    {
      namespace: "seo",
      name: "meta_title",
      type: "text",
      label: "Meta Title",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "meta_description",
      type: "text",
      label: "Meta Description",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "meta_keywords",
      type: "text",
      label: "Meta Keywords",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "sepHomePageSeo",
      type: "separator",
      label: "Home Page SEO",
      tab: "SEO",
      showInTable: false,
    },
    {
      namespace: "seo",
      name: "homePageSeoMetaTitle",
      type: "text",
      label: "Meta Title Home Page",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "homePageSeoMetaDescription",
      type: "text",
      label: "Meta Description Home Page",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "homePageSeoMetaKeywords",
      type: "text",
      label: "Meta Keywords Home Page",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "sepEventPageSeo",
      type: "separator",
      label: "Event Page SEO",
      tab: "SEO",
      showInTable: false,
    },
    {
      namespace: "seo",
      name: "eventPageSeoMetaTitle",
      type: "text",
      label: "Meta Title Event Page",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "eventPageSeoMetaDescription",
      type: "text",
      label: "Meta Description Event Page",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "eventPageSeoMetaKeywords",
      type: "text",
      label: "Meta Keywords Event Page",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "sepSearchRestaurantSeo",
      type: "separator",
      label: "Cari Resto SEO",
      tab: "SEO",
      showInTable: false,
    },
    {
      namespace: "seo",
      name: "searchRestaurantSeoMetaTitle",
      type: "text",
      label: "Meta Title Cari Resto",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "searchRestaurantSeoMetaDescription",
      type: "text",
      label: "Meta Description Cari Resto",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "searchRestaurantSeoMetaKeywords",
      type: "text",
      label: "Meta Keywords Cari Resto",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "sepContactPageSeo",
      type: "separator",
      label: "Contact Page SEO",
      tab: "SEO",
      showInTable: false,
    },
    {
      namespace: "seo",
      name: "contactPageSeoMetaTitle",
      type: "text",
      label: "Meta Title Contact Page",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "contactPageSeoMetaDescription",
      type: "text",
      label: "Meta Description Contact Page",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "contactPageSeoMetaKeywords",
      type: "text",
      label: "Meta Keywords Contact Page",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "sepAboutUsSeo",
      type: "separator",
      label: "About Us SEO",
      tab: "SEO",
      showInTable: false,
    },
    {
      namespace: "seo",
      name: "aboutUsSeoMetaTitle",
      type: "text",
      label: "Meta Title About Us",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "aboutUsSeoMetaDescription",
      type: "text",
      label: "Meta Description About Us",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "aboutUsSeoMetaKeywords",
      type: "text",
      label: "Meta Keywords About Us",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "sepBlogSeo",
      type: "separator",
      label: "Blog SEO",
      tab: "SEO",
      showInTable: false,
    },
    {
      namespace: "seo",
      name: "blogSeoMetaTitle",
      type: "text",
      label: "Meta Title Blog",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "blogSeoMetaDescription",
      type: "text",
      label: "Meta Description Blog",
      tab: "SEO",
    },
    {
      namespace: "seo",
      name: "blogSeoMetaKeywords",
      type: "text",
      label: "Meta Keywords Blog",
      tab: "SEO",
    },
    {
      namespace: "scripts",
      name: "headerScript",
      type: "textarea",
      label: "Header Script",
      tab: "Scripts",
    },
    {
      namespace: "scripts",
      name: "footerScript",
      type: "textarea",
      label: "Footer Script",
      tab: "Scripts",
    },
    {
      namespace: "socialMedia",
      name: "socialInstagram",
      type: "url",
      label: "Instagram",
      tab: "Social Media",
    },
    {
      namespace: "socialMedia",
      name: "socialFacebook",
      type: "url",
      label: "Facebook",
      tab: "Social Media",
    },
    {
      namespace: "socialMedia",
      name: "socialYoutube",
      type: "url",
      label: "Youtube",
      tab: "Social Media",
    },
    {
      namespace: "socialMedia",
      name: "socialLinkedin",
      type: "url",
      label: "LinkedIn",
      tab: "Social Media",
    },
    {
      namespace: "socialMedia",
      name: "socialLink",
      type: "url",
      label: "Custom Link",
      tab: "Social Media",
    },
    {
      namespace: "aboutUs",
      name: "aboutUsImage",
      type: "image",
      label: "Image",
      tab: "About Us",
      uploadUrl: "/api/upload?path=uploads/about-us",
    },
    {
      namespace: "aboutUs",
      name: "aboutUsTitle",
      type: "text",
      label: "Title",
      tab: "About Us",
    },
    {
      namespace: "aboutUs",
      name: "aboutUsContent",
      type: "text",
      label: "Content",
      tab: "About Us",
    },
    {
      namespace: "aboutUs",
      name: "aboutUsSubContent",
      type: "text",
      label: "Sub Content",
      tab: "About Us",
    },
    {
      namespace: "aboutUs",
      name: "aboutUsMainImage",
      type: "image",
      label: "Main Image",
      tab: "About Us",
      uploadUrl: "/api/upload?path=uploads/about-us",
    },
    {
      namespace: "aboutUs",
      name: "aboutUsMainTitle",
      type: "text",
      label: "Main Title",
      tab: "About Us",
    },
    {
      namespace: "aboutUs",
      name: "aboutUsMainContent",
      type: "richtext",
      label: "Main Content",
      tab: "About Us",
    },
    {
      namespace: "aboutUs",
      name: "aboutUsMainWriter",
      type: "text",
      label: "Main Writer",
      tab: "About Us",
    },
    {
      namespace: "aboutUs",
      name: "aboutUsMainWriterSign",
      type: "text",
      label: "Main Writer Sign",
      tab: "About Us",
    },
    {
      namespace: "contactPage",
      name: "contactPageImage",
      type: "image",
      label: "Headline Image",
      tab: "Contact Page",
      uploadUrl: "/api/upload?path=uploads/contact-page",
    },
    {
      namespace: "contactPage",
      name: "contactPageHeadline",
      type: "text",
      label: "Headline",
      tab: "Contact Page",
    },
    {
      namespace: "contactPage",
      name: "contactPageTitle",
      type: "text",
      label: "Title",
      tab: "Contact Page",
    },
    {
      namespace: "contactPage",
      name: "contactPageSubTitle",
      type: "text",
      label: "Subtitle",
      tab: "Contact Page",
    },
    {
      namespace: "contactPage",
      name: "contactPageFormImage",
      type: "image",
      label: "Form Image",
      tab: "Contact Page",
      uploadUrl: "/api/upload?path=uploads/contact-page",
    },
    {
      namespace: "contactPage",
      name: "contactPageFormDescription",
      type: "richtext",
      label: "Form Description",
      tab: "Contact Page",
    },
    {
      namespace: "contactPage",
      name: "contactPageFormTitle",
      type: "text",
      label: "Form Title",
      tab: "Contact Page",
    },
    {
      namespace: "contactPage",
      name: "contactPageFormSubTitle",
      type: "text",
      label: "Form Sub Title",
      tab: "Contact Page",
    },
    {
      namespace: "contactPage",
      name: "contactPageNote",
      type: "text",
      label: "Contact Note",
      tab: "Contact Page",
    },
    {
      namespace: "eventPage",
      name: "eventPageHeadline",
      type: "text",
      label: "Headline",
      tab: "Event Page",
    },
    {
      namespace: "eventPage",
      name: "eventPageTitle",
      type: "text",
      label: "Title",
      tab: "Event Page",
    },
    {
      namespace: "eventPage",
      name: "eventPageSubTitle",
      type: "text",
      label: "Subtitle",
      tab: "Event Page",
    },
    {
      namespace: "searchRestaurant",
      name: "searchRestaurantBanner",
      type: "image",
      label: "Banner",
      tab: "Search Restaurant",
      uploadUrl: "/api/upload?path=uploads/search-restaurant",
    },
    {
      namespace: "searchRestaurant",
      name: "searchRestaurantTitle",
      type: "text",
      label: "Title",
      tab: "Search Restaurant",
    },
    {
      namespace: "eventPage",
      name: "searchRestaurantSubTitle",
      type: "text",
      label: "Subtitle",
      tab: "Search Restaurant",
    },
  ],
});
