import { defineCRUD } from "@repo/crud";

export const StaticSectionCRUD = defineCRUD({
  model: "staticSection",
  label: "Static Section",
  mode: "keyValue", // switches UI to settings-style form
  navGroup: "Content", // optional sidebar group
  icon: "Globe",
  fields: [
    {
      namespace:"general",
      name: "logo",
      type: "image",
      label: "Logo",
      tab: "General",
      uploadUrl: "/api/upload?path=uploads/logo",
    },
    {
      namespace:"general",
      name: "favicon",
      type: "image",
      label: "Favicon",
      tab: "General",
      uploadUrl: "/api/upload?path=uploads/favicon",
    },
    { namespace:"general", name: "description", type: "text", label: "Description", tab: "General" },
    { namespace:"general", name: "phone", type: "text", label: "Phone", tab: "General" },
    { namespace:"general", name: "email", type: "email", label: "Email", tab: "General" },
    {
      namespace:"general",
      name: "opening_hours_day",
      type: "text",
      label: "Opening Hours Day",
      tab: "General",
    },
    {
      namespace:"general",
      name: "opening_hours_time",
      type: "text",
      label: "Opening Hours Time",
      tab: "General",
    },
    { namespace:"general", name: "meta_title", type: "text", label: "Meta Title", tab: "SEO" },
    { namespace:"general", name: "meta_description", type: "text", label: "Meta Description", tab: "SEO" },
    { namespace:"general", name: "meta_keywords", type: "text", label: "Meta Keywords", tab: "SEO" },
    {
      namespace:"about",
      name: "about_legend",
      type: "text",
      label: "Legend",
      tab: "About Section",
    },
    {
      namespace:"about",
      name: "about_title",
      type: "richtext",
      label: "Title",
      tab: "About Section",
      required: true,
    },
    {
      namespace:"about",
      name: "about_body",
      type: "richtext",
      label: "Body",
      tab: "About Section",
    },
    {
      namespace:"about",
      name: "about_ctaLabel",
      type: "text",
      label: "CTA Label",
      tab: "About Section",
    },
    {
      namespace:"about",
      name: "about_ctaUrl",
      type: "text",
      label: "CTA URL",
      tab: "About Section",
    },
    {
      namespace:"about",
      name: "about_photo",
      type: "image",
      label: "Photo",
      tab: "About Section",
      uploadUrl: "/api/upload?path=uploads/about",
    },
    {
      namespace:"gallery",
      name: "gallery_legend",
      type: "text",
      label: "Legend",
      tab: "Gallery Section",
    },
    {
      namespace:"gallery",
      name: "gallery_title",
      type: "richtext",
      label: "Title",
      tab: "Gallery Section",
      required: true,
    },
    {
      namespace:"gallery",
      name: "gallery_ctaLabel",
      type: "text",
      label: "CTA Label",
      tab: "Gallery Section",
    },
    {
      namespace:"gallery",
      name: "gallery_ctaUrl",
      type: "url",
      label: "CTA URL",
      tab: "Gallery Section",
    },
    { namespace:"video", name: "video_title", type: "richtext", label: "Title", tab: "Video Section" },
    { namespace:"video", name : "video_url", type: "url", label: "Video URL", tab: "Video Section" },
    {
      namespace:"video",
      name: "video_placeholder",
      type: "text",
      label: "Placeholder",
      tab: "Video Section",
    },
    {
      namespace:"location",
      name: "location_legend",
      type: "richtext",
      label: "Legend",
      tab: "Location Section",
    },
    {
      namespace:"location",
      name: "location_title",
      type: "richtext",
      label: "Title",
      tab: "Location Section",
    },
    {
      namespace:"blog",
      name: "blog_legend",
      type: "richtext",
      label: "Legend",
      tab: "Blog Section",
    },
    {
      namespace:"blog",
      name: "blog_title",
      type: "richtext",
      label: "Title",
      tab: "Blog Section",
    },
    { namespace:"social", name: "social_facebook", type: "url", label: "Facebook", tab: "Social" },
    {
      namespace:"social",
      name: "social_instagram",
      type: "url",
      label: "Instagram",
      tab: "Social",
    },
    {
      namespace:"social",
      name: "social_twitter",
      type: "url",
      label: "Twitter / X",
      tab: "Social",
    },
    { namespace:"social", name: "social_youtube", type: "url", label: "YouTube", tab: "Social" },
    { namespace:"social", name: "social_tiktok", type: "url", label: "TikTok", tab: "Social" },
    { namespace:"social", name: "social_linkedin", type: "url", label: "LinkedIn", tab: "Social" },
    { namespace:"social", name: "social_whatsapp", type: "url", label: "WhatsApp", tab: "Social" },
    { namespace:"contact", name: "contact_number", type: "text", label: "WhatsApp general number", tab: "Contact" },
  ],
});
