import { defineCRUD } from "@repo/crud";

export const SettingsCRUD = defineCRUD({
  model: "settings",
  label: "Settings",
  mode: "keyValue",
  navGroup: "Administration",
  fields: [
    {
      name: "brandingAppName",
      type: "text",
      label: "App Name",
      tab: "Branding",
      namespace: "branding",
    },
    {
      name: "brandingLogoLightUrl",
      type: "image",
      label: "Logo (Light Mode)",
      tab: "Branding",
      namespace: "branding",
      uploadUrl: "/api/upload?path=uploads/admin/settings",
      note: "Recommended size: 512x512px square PNG or SVG.",
      width: "half",
    },
    {
      name: "brandingLogoDarkUrl",
      type: "image",
      label: "Logo (Dark Mode)",
      tab: "Branding",
      namespace: "branding",
      uploadUrl: "/api/upload?path=uploads/admin/settings",
      note: "Recommended size: 512x512px square PNG or SVG.",
      width: "half",
    },
    {
      name: "brandingFaviconUrl",
      type: "image",
      label: "Favicon",
      tab: "Branding",
      namespace: "branding",
      uploadUrl: "/api/upload?path=uploads/admin/settings",
      note: "Recommended size: 512x512px square PNG or SVG.",
    },
    {
      name: "brandingLoginTitle",
      type: "textarea",
      label: "Login Title",
      tab: "Branding",
      namespace: "branding",
      note: "Shown on the login page hero. Line breaks are preserved.",
    },
    {
      name: "brandingLoginSubtitle",
      type: "textarea",
      label: "Login Subtitle",
      tab: "Branding",
      namespace: "branding",
      note: "Shown below the login page hero title.",
    },
    {
      name: "emailEnabled",
      type: "boolean",
      label: "Enable email delivery",
      tab: "Email",
      namespace: "email",
      default: false,
      note: "When disabled, server email sends fail before contacting the provider.",
    },
    {
      name: "emailProvider",
      type: "select",
      label: "Provider",
      tab: "Email",
      namespace: "email",
      options: [
        { label: "Resend", value: "resend" },
        { label: "Amazon SES", value: "ses" },
      ],
      default: "resend",
      visibleWhen: { field: "emailEnabled", equals: true },
      note: "Choose the active transactional email provider.",
    },
    {
      name: "emailFromEmail",
      type: "email",
      label: "From Email",
      tab: "Email",
      namespace: "email",
      width: "half",
      visibleWhen: { field: "emailEnabled", equals: true },
    },
    {
      name: "emailFromName",
      type: "text",
      label: "From Name",
      tab: "Email",
      namespace: "email",
      width: "half",
      visibleWhen: { field: "emailEnabled", equals: true },
    },
    {
      name: "emailReplyTo",
      type: "email",
      label: "Reply-to Email",
      tab: "Email",
      namespace: "email",
      visibleWhen: { field: "emailEnabled", equals: true },
      note: "Optional. Replies go to this address instead of the from address.",
    },
  ],
});
